/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 book_stand.glb
Author: Asylum Nox (https://sketchfab.com/peter.pottiez)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wizard-book-stand-18d694bb036648bfb8b878e5164a5100
Title: Wizard Book Stand
*/

import React, { useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { TextureLoader } from 'three';
import { useLoader } from '@react-three/fiber';

function Model(props) {
  const { nodes, materials, textures } = useGLTF('/book_stand.glb')
  const colorMap = useLoader(TextureLoader, 'texture01.jpg');

  // State values for hover
  const [hovered, setHover] = useState(false);
  return (
    <group {...props} dispose={null}
        onPointerOver={(event) => setHover(true)}
        onPointerOut={(event) => setHover(false)}
    >
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.45}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials['Material.00_Material.001_gen_ligh']} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials['Material.002_material_flaskthing.d']}>
            <meshStandardMaterial map={colorMap} color={hovered ? "lightgreen" : "white"} />
          </mesh>
{/*}      <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials.Material_lootchest_ezmo_stuff} >
            <meshStandardMaterial color={hovered ? "hotpink" : "orange"} />
          </mesh>{*/}
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/book_stand.glb');

export default Model;