/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 paper_pen_one.glb 
Author: abhijithsince2002 (https://sketchfab.com/abhijithsince2002)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/paper-pen-one-6e7f94bc4fd845e48abee51f2e5c6153
Title: Paper pen one
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/paper_pen_one.glb')
  const { actions } = useAnimations(animations, group);

  actions.Animation.play();

  console.log(actions.AnimationAction);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="polySurface18_37" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.aiStandardSurface2} />
                <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.Pen_And_Paper_lambert2} />
                <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.lambert2} />
              </group>
              <group name="group1_30" position={[0.001, -0.02, -0.014]} rotation={[2.308, -0.39, -0.133]} scale={0.01}>
                <group name="polySurface2_29">
                  <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials.Pen_And_Paper_lambert2} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/paper_pen_one.glb')
